CREATE DATABASE IF NOT EXISTS santa_teresa;
USE santa_teresa;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  endereco TEXT NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  passaporte VARCHAR(20) UNIQUE NOT NULL,
  nacionalidade VARCHAR(50) NOT NULL,
  telefone VARCHAR(20),
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);